### ISSUE TITLE
only need the camera intrinsic parameters?

### ISSUE THREAD

**Issue by qiuzhongwei-USTB** [facebookresearch/VideoPose3D#101]
hi,

Thanks your great work. I have a question about your Semi-supervised method.

Are you regression 3d coordinates in the world coordinate system?
if true, it's seemed that extrinsic  parameters are also need to project 3d coordinates to 2d coordinates.

Could you help me solve my confusion? Thanks

**Comment by dariopavllo** [comment]
Hi,

Since the prediction is always in *camera space*, you don't need the extrinsic parameters for the semi-supervised method.

Of course, when you train the model in a supervised fashion, you need the extrinsic parameters to convert the 3D poses of your dataset from world space to camera space (if the dataset is not already in this format).
