### ISSUE TITLE
 Should MPJPE be averaged on 16 joints or 17 joints?

### ISSUE THREAD

**Issue by KevinLTT** [facebookresearch/VideoPose3D#16]
Hi, firstly thanks for your code. 
I have a question about the way you calculate MPJPE. According to your code, the root joint position of the target 3D poses is set as [0, 0, 0], and calculate MPJPE with the predicted ones.
```python
# line 428 in run.py
inputs_3d[:, :, 0] = 0

# Predict 3D poses
predicted_3d_pos = model_pos(inputs_2d)
loss_3d_pos = mpjpe(predicted_3d_pos, inputs_3d)
```
This means that your MPJPE is averaged on 17 joints.
However, in some other evaluation, for example https://github.com/rayat137/Pose_3D, MPJPE is averaged on 16 joints， and the root is not involved in.

I want to know which one is correct, 16 or 17?

**Comment by dariopavllo** [comment]
Hi,

We evaluate on 17 joints, which is the standard protocol, as in [Martinez et al. '17](https://github.com/una-dinosauria/3d-pose-baseline).

I think that in the repo you linked, the evaluation is also done on 17 joints. Look [here](https://github.com/rayat137/Pose_3D/blob/master/temporal_3d_release/temporal_3d.py#L252-L254) and [here](https://github.com/rayat137/Pose_3D/blob/master/temporal_3d_release/temporal_3d.py#L304-L309).

Since the standard protocol removes the global trajectory, the root joint position is subtracted from all joints, and the root joint itself becomes zero. We however keep the original position in the first index for semi-supervised experiments (this is just an implementation detail that comes handy), and in supervised experiments we just set it to zero explicitly.

**Comment by KevinLTT** [comment]
Thanks!
