### ISSUE TITLE
Causality and video padding

### ISSUE THREAD

**Issue by achigeor** [facebookresearch/VideoPose3D#44]
Hi and thanks a lot for releasing your code!

I have a question regarding the padding of videos in the case of causal convolutions. Sorry if that's answered elsewhere or in the paper, it's not very clear to me :)

Looking at figure 9a of the paper (symmetric case), it's clear that for the first and last frames of the video (depending on the receptive field), the network "sees" duplicate frames due to padding. In the example in 9a, the most extreme case for symmetric convolutions are the 2  first and 2 last frames, where you get the only duplicate frames left and right respectively. 

While in the extreme cases for symmetric convs the samples still include some non-duplicate frames (future or past depending on position in the video), for causal convolutions we have more extreme cases, where for the first 2 frames the network sees samples that are pretty much only padding, i.e. the same frame duplicated `receptive_field -1` times. 

So my questions for the causal case are:
* Is the assumption is that the network is robust enough to differentiate between these cases 
(all duplicated past frames VS actual past frames)?
* Did you run any experiments for causal convolutions where you discard these extreme cases and never present them as samples to the network? If yes, was there any change in performance? I guess it's hard to evaluate whole videos in that case, since you can only get predictions for frames where `frame_id >= receptive_field` if you discard all cases with padding.

Hope my questions make sense :D

Thanks!

**Comment by dariopavllo** [comment]
Hi,

Your questions make sense!

Since the model has been trained in this way (padding boundary frames by replication), it should learn to be robust to these cases (at least to some extent). By looking at some qualitative results, we did not notice anything odd for the first/last frames. The model just behaves as if it were a single-frame model, or as if the person were in a still pose (in a video).

This is also why we pad by replication instead of zero-padding. Padding with zeros would lead to a discontinuous representation space and would cause some glitches in the first/last frames.

Regarding evaluation, we did not try to discard these frames, as that would lead to biased results. We had to be consistent with previous evaluation methodologies.

**Comment by achigeor** [comment]
Thanks for the quick reply @dariopavllo, helps a lot!

> the model just behaves as if it were a single-frame model, or as if the person were in a still pose (in a video).

Actually makes a lot of sense. So I guess in the most extreme cases of causal convolutions, this effect is very strong (stronger than symmetric convolutions), so it would feel like the model is "buffering" (or lagging) until the input has a (arbitrary) number of non-duplicate frames? 

Your answer already covered me, just asking because it's interesting to check the behaviour of the model in these edge cases :)

**Comment by dariopavllo** [comment]
No, I don't think the model would buffer (or if it does, it would be unnoticeable). The goal of causal convolutions is to avoid this effect, since in principle you could always do real-time prediction with symmetric convolutions if you are willing to accept a small delay (half the receptive field).

The model learns to combine the different frames in order to yield a stable prediction (since it's a feed-forward network, it has no memory), with the frame at position 0 having the largest effect. For the first few frames, the model just uses what it has (replicated boundary frames), as if the person were not moving in a video.

**Comment by achigeor** [comment]
Got it! Thanks a lot!
